### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by teobais** [HugoGiraudel/scrabble-helper#1]

**Comment by KittyGiraudel** [comment]
What is not working on Windows right now? :)

**Comment by teobais** [comment]
I get the following error, while executing a command: 

![image](https://cloud.githubusercontent.com/assets/5684688/17831636/822f88f6-66ee-11e6-8165-3ecbdbe7ecf0.png)

**Comment by KittyGiraudel** [comment]
Which version of Node are you running?

**Comment by teobais** [comment]
v4.4.0

**Comment by KittyGiraudel** [comment]
Do you mind trying with v6+? If that works, we need to force the version in package.json.

**Comment by teobais** [comment]
In the site of node, it mentions that the latest is 4.5, so, I downloaded [this](https://nodejs.org/en/blog/release/v6.4.0/) one and I now seem to have v0.12.2, instead.
In addition, I now receive an error a line prior to the previous one:

![image](https://cloud.githubusercontent.com/assets/5684688/17833295/48a4ec86-6719-11e6-85b8-4e54dc66ae47.png)

**Comment by KittyGiraudel** [comment]
No version 6 on Windows?

<img width="594" alt="screen shot 2016-08-20 at 21 03 50" src="https://cloud.githubusercontent.com/assets/1889710/17833306/9f737b04-6719-11e6-9cdb-6ccbf0a22d5e.png">

**Comment by KittyGiraudel** [comment]
I highly recommend you use nvm to manage your Node.js version.
